version: 2

jobs:
  push:
    machine: true
    steps:
      - checkout
      - run:
          name: Rebuild docker image and push to registry
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            source ~/.bashrc
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            cd webapp
            make pull
            make build
            make push
            cd ../server
            make pull
            make build
            make push
  production:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:be:05:27:97:c4:1c:8e:6b:0e:a5:ed:2e:bf:aa:4f"
      - run: ssh root@82.223.82.41 "bash -ic deploy-weakly-web-production"

workflows:
  version: 2
  deploy:
    jobs:
      - push:
          filters:
            branches:
              only: master
      - production:
          requires:
            - push
          filters:
            branches:
              only: master
