version: 2

jobs:
  build:
    machine:
      image: circleci/node
    steps:
      - checkout
      - run:
          name: Rebuild docker image and push to registry
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            cd webapp
            make pull
            make build
            make push
            cd ../server
            make pull
            make build
            make push
  production:
    machine:
      image: circleci/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:be:05:27:97:c4:1c:8e:6b:0e:a5:ed:2e:bf:aa:4f"
      - run: ssh root@82.223.82.41 "bash -ic deploy-weakly-web-production"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - production:
          requires:
            - build
          filters:
            branches:
              only: master
